server {
    listen 80;
    server_name kiniedx.com www.kiniedx.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://www.kiniedx.com$request_uri;
    }
}
