export const ROUTES = {
  PUBLIC: {
    HOME: "/",
    ABOUT: "/about",
    BLOG: "/blog",
    CAREER: "/career",
    CONTACT: "/contact",
    MENTORS: "/mentors",
    FAQ: "/faq",
    FEATURES: "/features",
    MISSION_VISION: "/mission-vision",
    WHO_WE_ARE: "/who-we-are",
    ORGANIZATION_STRUCTURE: "/organization-structure",
    TEAM_GALLERY: "/team-gallery",
    WHY_CHOOSE_US: "/why-choose-us",
    WHY_CHOOSE_US_ABOUT: "/why-choose-us-about",
    FOUNDER_SECTION: "/founder-section",
    STUDENT_REVIEWS: "/student-reviews",
    SUCCESS_STORIES: "/success-stories",
    LIGHTFALL: "/lightfall",
    UPSKILL_PROGRAM: "/upskill-program",
    ADMISSIONS: "/admissions",
    COURSES: "/courses",
    AI_ENGINEERING_IMMERSIVE: "/ai-engineering-immersive",
    PROJECT_NEW: "/project-new",
    PLACEMENT: "/placement",
    STUDENTS: "/students",
    DASHBOARD: "/dashboard",
  },
};
